/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

public class TimKiemDVGUI extends javax.swing.JFrame {

    /**
     * Creates new form TimKiemDV
     */
    public TimKiemDVGUI() {
        initComponents();
        jHienThi.setModel(model);
    }
       DefaultTableModel model = TimTTDoanVienForm.TimDVModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jHienThi = new javax.swing.JTable();
        btnTimDV = new javax.swing.JButton();
        btnTimLai = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        tcombo = new javax.swing.JComboBox<>();
        txtFindValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jHienThi);

        btnTimDV.setText("Tìm Đoàn viên");
        btnTimDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimDVActionPerformed(evt);
            }
        });

        btnTimLai.setText("Tìm lại");
        btnTimLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimLaiActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        tcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã  Đoàn viên", "Tên Đoàn viên", "Mã Chi đoàn" }));

        txtFindValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTimDV)
                                .addGap(33, 33, 33)
                                .addComponent(btnTimLai, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(tcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(txtFindValue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFindValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimDV)
                    .addComponent(btnTimLai)
                    .addComponent(btnQuayLai))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimDVActionPerformed
    String valueCombobox=null;
    if(tcombo.getSelectedItem().toString() == "Mã  Đoàn viên"){
       valueCombobox = "MaDV";
    } 
    else if(tcombo.getSelectedItem().toString() == "Tên Đoàn viên"){
       valueCombobox = "TenDV";
    } 
    else if(tcombo.getSelectedItem().toString() == "Mã Chi đoàn"){
       valueCombobox = "MaChiDoan"; 
    }
        ArrayList<DTO.TTDoanVien> xuly =  TimTTDoanVienForm.FindDV(valueCombobox,txtFindValue.getText());
        
        try {
            model.getDataVector().removeAllElements();
            jHienThi.setModel(model);
            for(int i = 0 ; i <xuly.size();i++){
                Vector<String> h = new Vector<>();
                h.add(xuly.get(i).getMaDV());
                h.add(xuly.get(i).getHoDV());
                h.add(xuly.get(i).getTenDV());
                h.add(xuly.get(i).getNgaySinh());
                h.add(xuly.get(i).getGioiTinh());
                h.add(xuly.get(i).getQueQuan());
                h.add(xuly.get(i).getEmail());
                h.add(xuly.get(i).getSDT());
                h.add(xuly.get(i).getDanToc());
                h.add(xuly.get(i).getTonGiao());
                h.add(xuly.get(i).getNgayVaoDoan());
                h.add(xuly.get(i).getChooHienNay());
                h.add(xuly.get(i).getMaChiDoan());
           
                model.addRow(h);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi:" +e);
        }
        
    }//GEN-LAST:event_btnTimDVActionPerformed

    private void btnTimLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimLaiActionPerformed
       txtFindValue.setText("");
      
        
        model.getDataVector().removeAllElements();
    }//GEN-LAST:event_btnTimLaiActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
         setVisible(false);
        dispose();
        new QLDV().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void txtFindValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemDVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemDVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemDVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemDVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiemDVGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnTimDV;
    private javax.swing.JButton btnTimLai;
    private javax.swing.JTable jHienThi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> tcombo;
    private javax.swing.JTextField txtFindValue;
    // End of variables declaration//GEN-END:variables
}
