/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.HDBan1Form;
import BLL.Hang1Form;
import BLL.Khach1Form;
import BLL.NhanVien1Form;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class HDBan1GUI extends javax.swing.JFrame {

    /**
     * Creates new form HDBan1GUI
     */
    public HDBan1GUI() {
        initComponents();
          jHienThi.setModel(model);
        ThemItemcb();
    }
 DefaultTableModel model = HDBan1Form.HDBanModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmhd = new javax.swing.JTextField();
        txtnb = new javax.swing.JTextField();
        txttnv = new javax.swing.JTextField();
        jmnv = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jmkh = new javax.swing.JComboBox<>();
        txttkh = new javax.swing.JTextField();
        txtdc = new javax.swing.JTextField();
        txtdt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtdg = new javax.swing.JTextField();
        txttt = new javax.swing.JTextField();
        txtth = new javax.swing.JTextField();
        txtgg = new javax.swing.JTextField();
        jmh = new javax.swing.JComboBox<>();
        txtsl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jHienThi = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttgt = new javax.swing.JTextField();
        btnlhd = new javax.swing.JButton();
        btnshd = new javax.swing.JButton();
        btnth = new javax.swing.JButton();
        btnxhd = new javax.swing.JButton();
        btndong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chung"));

        jLabel1.setText("Mã hóa đơn");

        jLabel2.setText("Ngày bán");

        jLabel3.setText("Mã nhân viên");

        jLabel4.setText("Tên nhân viên");

        jmnv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jmnvItemStateChanged(evt);
            }
        });

        jLabel5.setText("Mã khách hàng");

        jLabel6.setText("Tên khách hàng");

        jLabel7.setText("Địa chỉ");

        jLabel8.setText("Điện thoại");

        jmkh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jmkhItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txttnv)
                    .addComponent(jmnv, 0, 125, Short.MAX_VALUE)
                    .addComponent(txtnb)
                    .addComponent(txtmhd))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttkh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmkh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jmkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttkh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jmnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(txttnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtdt)))
                .addGap(25, 25, 25))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin các mặt hàng"));

        jLabel9.setText("Mã hàng");

        jLabel10.setText("Số lượng");

        jLabel11.setText("Tên hàng");

        jLabel12.setText("Giảm giá %");

        jLabel13.setText("Đơn giá");

        jLabel14.setText("Thành tiền");

        jmh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jmhItemStateChanged(evt);
            }
        });

        jHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jHienThi);

        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("Nháy đúp một dòng để xóa ");

        jLabel16.setText("Tổng tiền");

        btnlhd.setText("Lưu hóa đơn");
        btnlhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlhdActionPerformed(evt);
            }
        });

        btnshd.setText("Sửa hóa đơn");
        btnshd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshdActionPerformed(evt);
            }
        });

        btnth.setText("Thêm hàng");
        btnth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthActionPerformed(evt);
            }
        });

        btnxhd.setText("Xóa hóa đơn");
        btnxhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxhdActionPerformed(evt);
            }
        });

        btndong.setText("Đóng");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnlhd)
                        .addGap(86, 86, 86)
                        .addComponent(btnshd)
                        .addGap(62, 62, 62)
                        .addComponent(btnth)
                        .addGap(89, 89, 89)
                        .addComponent(btnxhd)
                        .addGap(68, 68, 68)
                        .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jmh, 0, 114, Short.MAX_VALUE)
                            .addComponent(txtsl))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(20, 20, 20)
                                .addComponent(txtgg))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(29, 29, 29)
                                .addComponent(txtth, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(58, 58, 58)
                            .addComponent(jLabel16)
                            .addGap(30, 30, 30)
                            .addComponent(txttgt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(341, 341, 341))))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(txtdg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(txttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlhd)
                    .addComponent(btnshd)
                    .addComponent(btnth)
                    .addComponent(btnxhd)
                    .addComponent(btndong))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Thông tin chung");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlhdActionPerformed
          String MaHDBan = txtmhd.getText();
        String MaNhanVien = jmnv.getSelectedItem().toString();
        String NgayBan = txtnb.getText();
        String MaKhachHang = jmkh.getSelectedItem().toString();
        Float TongTien = Float.parseFloat(txttgt.getText());
        int kq = HDBan1Form.InsertHDBan(MaHDBan, MaNhanVien, NgayBan, MaKhachHang,TongTien);
        if(kq == 0){
            JOptionPane.showMessageDialog(rootPane, "Lưu hóa đơn thất bại! \n Trùng mã hóa đơn","ERROR",JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Lưu thành công","THÔNG BÁO", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnlhdActionPerformed

    private void btnshdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshdActionPerformed
         String MaHDBan = txtmhd.getText();
        String MaNhanVien = jmnv.getSelectedItem().toString();
        String NgayBan = txtnb.getText();
        String MaKhachHang = jmkh.getSelectedItem().toString();
        Float TongTien = Float.parseFloat(txttgt.getText());
        int kq = HDBan1Form.UpdateHDBan(MaHDBan, MaNhanVien, NgayBan, MaKhachHang,TongTien);
        if(kq == 0){
            JOptionPane.showMessageDialog(rootPane, "Sửa hóa đơn thất bại!","ERROR",JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sửa hóa đơn thành công","THÔNG BÁO", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnshdActionPerformed

    private void btnthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthActionPerformed
        String MaHang = jmh.getSelectedItem().toString();
        String TenHang = txtth.getText();
        float DonGia = Float.parseFloat(txtdg.getText());
        float SoLuong = Float.parseFloat(txtsl.getText());
        float GiamGia = Float.parseFloat(txtgg.getText());
        float ThanhTien = (DonGia*SoLuong) - (((DonGia * SoLuong)*GiamGia)/100);
        txttt.setText(String.valueOf(ThanhTien));
        
        Vector <String> h = new Vector<>();
        h.add(MaHang);
        h.add(TenHang);
        h.add(txtsl.getText());
        h.add(txtdg.getText());
        h.add(txtgg.getText()+"%");
        h.add(txttt.getText());
        model.addRow(h);
        jHienThi.setModel(model);
        float Tong = 0;
        for(int i = 0 ; i < jHienThi.getRowCount();i++){
            Tong += Float.parseFloat(model.getValueAt(i, 5).toString());
        }
        txttgt.setText(String.valueOf(Tong));
    }//GEN-LAST:event_btnthActionPerformed

    private void btnxhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxhdActionPerformed
        int kq = HDBan1Form.DeleteHDBan (txtmhd.getText());
        if(kq == 0){
            JOptionPane.showMessageDialog(rootPane, "Xóa hóa đơn thất bại!","ERROR",JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xóa hóa đơn thành công","THÔNG BÁO", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnxhdActionPerformed

    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
         setVisible(false);
        dispose();
        new QLBH().setVisible(true);
    }//GEN-LAST:event_btndongActionPerformed

    private void jmkhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jmkhItemStateChanged
              String MaKhach = jmkh.getSelectedItem().toString();
        txttkh.setText(HDBan1Form.TenKhachHDBan(MaKhach));
        txtdc.setText(HDBan1Form.DCKhachHDBan(MaKhach));
        txtdt.setText(HDBan1Form.DTKhachHDBan(MaKhach));
    }//GEN-LAST:event_jmkhItemStateChanged

    private void jmnvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jmnvItemStateChanged
       String MaNhanVien = jmnv.getSelectedItem().toString();
        txttnv.setText(HDBan1Form.TenNVHDBan(MaNhanVien));
    }//GEN-LAST:event_jmnvItemStateChanged

    private void jmhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jmhItemStateChanged
       String MaHang = jmh.getSelectedItem().toString();
        txtth.setText(HDBan1Form.TenHangHDBan(MaHang));
        txtdg.setText(HDBan1Form.DonGiaHDBan(MaHang));
        txtsl.setText("");
        txtgg.setText("");
        txttt.setText("");
    }//GEN-LAST:event_jmhItemStateChanged
private void ThemItemcb(){
        //THÊM ITEM CHO COMBOBOX
        for(int i = 0; i < NhanVien1Form.NhanVienArray().size();i++){
            jmnv.addItem(NhanVien1Form.NhanVienArray().get(i).getMaNhanVien());
        }
        for(int j = 0; j < Hang1Form.HangArray().size(); j++){
           jmh.addItem(Hang1Form.HangArray().get(j).getMaHang());
        }
        for(int k = 0; k < Khach1Form.KhachArray().size(); k++){
            jmkh.addItem(Khach1Form.KhachArray().get(k).getMaKhach());
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HDBan1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HDBan1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HDBan1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HDBan1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HDBan1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndong;
    private javax.swing.JButton btnlhd;
    private javax.swing.JButton btnshd;
    private javax.swing.JButton btnth;
    private javax.swing.JButton btnxhd;
    private javax.swing.JTable jHienThi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jmh;
    private javax.swing.JComboBox<String> jmkh;
    private javax.swing.JComboBox<String> jmnv;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtdg;
    private javax.swing.JTextField txtdt;
    private javax.swing.JTextField txtgg;
    private javax.swing.JTextField txtmhd;
    private javax.swing.JTextField txtnb;
    private javax.swing.JTextField txtsl;
    private javax.swing.JTextField txttgt;
    private javax.swing.JTextField txtth;
    private javax.swing.JTextField txttkh;
    private javax.swing.JTextField txttnv;
    private javax.swing.JTextField txttt;
    // End of variables declaration//GEN-END:variables
}
